version: '3'
services:
  openproject:
    image: openproject/openproject:14.3
    container_name: openproject-container
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret123
      - OPENPROJECT_HOST__NAME=192.168.102.127:8080
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_DEFAULT__LANGUAGE=en
    ports:
      - "8080:8080"
    volumes:
      - openproject-data:/var/openproject/assets
    networks:
      - classroom-network

volumes:
  openproject-data:

networks:
  classroom-network:
